# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Arkectl < Formula
  desc ""
  homepage "https://github.com/arkemishub/homebrew-arkectl"
  version "0.0.5"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/arkemishub/arkectl/releases/download/v0.0.5/arkectl_Darwin_x86_64.tar.gz"
      sha256 "72f4b1088685e4793feec8b7c24d4c27b04c62f75a77575d5397cd9d51128c4f"

      def install
        bin.install "arkectl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/arkemishub/arkectl/releases/download/v0.0.5/arkectl_Darwin_arm64.tar.gz"
      sha256 "99a88d9073ae06a3fb34077a3e5d9cadad900ab98efdae33cd5dd65a68964278"

      def install
        bin.install "arkectl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/arkemishub/arkectl/releases/download/v0.0.5/arkectl_Linux_arm64.tar.gz"
      sha256 "be54e21e4dcdbf2b4f7c7aa9fe5c35b9e6f2b475a2a1adaa637031ab5e9f0de0"

      def install
        bin.install "arkectl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/arkemishub/arkectl/releases/download/v0.0.5/arkectl_Linux_x86_64.tar.gz"
      sha256 "f735090ca10bf2e1cff6a051a48fb74ab50ba7cb70c50b62d2761dc2b28b50e2"

      def install
        bin.install "arkectl"
      end
    end
  end
end
